### ISSUE TITLE
Tilt + Zoom is glitching please advise.

### ISSUE THREAD

**Issue by kerinzeebart** [microdee/UE4-SpaceMouse#61] opened 2021-11-10 15:38 UTC
Hi,
I got the plugin via unreal marketplace for 4.27 and I'm having this issue:
https://www.youtube.com/watch?v=d1J8nME5JYM
It seems like it is kinda zooming. Kind Regards

**Comment by microdee** [comment] 2021-11-10 16:42
this is a duplicate of https://github.com/microdee/UE4-SpaceMouse/issues/12
disable mouse scroll-wheel emulation in 3DxWare per-application device settings (by default opened via the "Menu" button on your device or the Left button on Space Navigators iirc while UE4 is the foreground application)

**Comment by kerinzeebart** [comment] 2021-11-10 17:51
Thanks this resolved the issue:
![obraz](https://user-images.githubusercontent.com/4799087/141166410-c41f1d68-9c29-4cec-8bc5-e0ce349429c8.png)

**Closed** 2021-11-10 18:19 UTC
