### ISSUE TITLE
ERROR: Missing precompiled manifest for 'SpaceMouseReader'

### ISSUE THREAD

**Issue by DanMcLaughlin** [microdee/UE4-SpaceMouse#7] opened 2020-05-16 14:31 UTC
Apologies if this is a newbie error but I'm just starting out with UE

I have a project which is just the default FPS template (added a few things to it for learning), I also have the wonderful UE4-SpaceMouse enabled. This is running 4.25.0, on Packaging on Windows I get

```
UATHelper: Packaging (Windows (64-bit)):   ERROR: Missing precompiled manifest for 'SpaceMouseReader'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in SpaceMouseReader.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'SpaceMouseReader'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in SpaceMouseReader.build.cs to override.
```
How do I fix this, is it an issue with my system or with SpaceMouse? Thanks so much

**Comment by microdee** [comment] 2020-05-17 00:31
Closing issue as this is duplicate of #5 
temporarily you can move this plugin from engine plugins to the project plugins, it was working for me. At one point I will have time to fix it hopefully.

**Comment by microdee** [comment] 2020-05-17 00:33
eh reopening it because that fella was "launching" not "packaging" but the issue is related regardless

**Comment by microdee** [comment] 2020-09-02 21:29
hey! good news, I fixed this very issue today. Can you try the latest release? https://github.com/microdee/UE4-SpaceMouse/releases/latest

**Comment by DanMcLaughlin** [comment] 2020-09-02 23:33
Funny I was just thinking of it this morning. Brilliant - thanks so much! Yes it packages now (well it doesn't due to another error, but no problem from the SpaceMouse). Really appreciate your work, I'm absolutely dependent on this for quickly navigating around the viewport. When you can get a change to do the enhancement for going inactive when UE4 is not the foreground app I'll be in heaven. Thanks again!

**Closed** 2020-09-13 02:35 UTC

**Comment by mhossein1384** [comment] 2022-02-01 14:35
> https://github.com/microdee/UE4-SpaceMouse/releases/latest

what should i do with mac?

**Comment by microdee** [comment] 2022-02-02 00:39
> > https://github.com/microdee/UE4-SpaceMouse/releases/latest
> 
> what should i do with mac?
> 

Sell it and buy a better PC for its price :D

But on a more serious note this plugin will not work on MacOS due to the unfortunate decisions apple has made regarding their USB access. This plugin is fully supported only on Windows and supposedly works on Linux as well due to a recent PR.
