### ISSUE TITLE
When the camera direction is close to Z axis, the control direction will be messed up

### ISSUE THREAD

**Issue by LynxWill** [microdee/UE4-SpaceMouse#27] opened 2021-01-25 05:51 UTC
Somersaults like airplanes can’t be allowed。
ue4.26
spacemouse1.1.0

It's ue4.26 problem, 4.25 doesn't have this problem at all

**Comment by microdee** [comment] 2021-01-26 03:39
Which camera mode are you using? In free-fly with roll you shouldn't have any inherent problem, when you're using a mode without roll you might encounter the gimbal lock problem, I have a plan to eliviate confusion about that.
I will try it tomorrow because even if it's an unwanted / confusing behavior, it shouldn't be different on separate engine versions. Also make sure the 3DConnexion's own plugin is disabled.

**Comment by LynxWill** [comment] 2021-01-26 04:07
> Which camera mode are you using? In free-fly with roll you shouldn't have any inherent problem, when you're using a mode without roll you might encounter the gimbal lock problem, I have a plan to eliviate confusion about that.
> I will try it tomorrow because even if it's an unwanted / confusing behavior, it shouldn't be different on separate engine versions. Also make sure the 3DConnexion's own plugin is disabled.

thanks for reply.

Any mode has this problem, and I did disable the 3dx plugin.  

I tried the 0.8 to 1.1 version of the plug-in and all had the same problem in 4.26, but everything is normal in 4.25. 

This strange behavior Because I often work in space scenes, I need to flexibly control the camera in each axis , and I did not have such a problem before 4.26.

**Comment by microdee** [comment] 2021-01-29 00:51
I could reproduce I guess what you're also experiencing, when the camera roll got flipped over beyond a threshold, the controls suddenly change axes, maan I wonder why on earth epic needed to change the behavior of those functions, I'll try to fix it

**Comment by microdee** [comment] 2021-01-29 04:22
fixed for next release, while I was there Orbiting behaviors got major improvements too

**Comment by LynxWill** [comment] 2021-01-29 04:32
Thanks a lot.
By the way, I think your plugin is much better than 3dx, simple and effective.

**Comment by microdee** [comment] 2021-02-03 15:56
if this problem is gone for you with new release (1.1.1) I'm closing this issue then, feel free to reopen if it didn't

**Closed by microdee** 2021-02-03 15:56 UTC
